apiVersion: v1
kind: Service
metadata:
  name: wpprod
  namespace: production
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp-80
  selector:
      app: wpprod
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-pass
  namespace: production
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: Njg5NWFndGtlbXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wpprod
  namespace: production
spec:
  selector:
    matchLabels:
      app: wpprod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wpprod
    spec:
      containers:
      - name: wpprod
        image: rizalkemas68/wp:1.0
        ports:
          - containerPort: 80
        env:
          - name: DB_HOST
            value: database-2.cemceonxlenm.us-east-2.rds.amazonaws.com
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass 
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: DB_PASS
     
