apiVersion: v1
kind: PersistentVolume
metadata:
 name: wpprod-disk2
 namespace: production
 labels:
     type: nfs-kubernetes
spec:
 storageClassName: aws-efs2
 capacity:
     storage: 60Gi
 accessModes:
     - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 nfs:
     path: /
     server: 10.10.1.107
     readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpprod-pvc2
  namespace: production
spec:
  storageClassName: aws-efs2
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi