apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus
  namespace: monitoring
  labels:
      env: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
      requests:
        storage: 2Gi
  storageClassName: gp2
