apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-prometheus
  namespace: monitoring
  labels:
      env: monitoring
spec:
  storageClassName: gp2
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"