apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
      type: amazonEBS
spec:
  storageClassName: gp2
  capacity:
      storage: 10Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
      volumeID: vol-035b762b5e0784d49
      fsType: ext4

