apiVersion: v1
kind: Service
metadata:
  name: sosmedstaging
  namespace: staging
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: tcp-80
  selector:
      run: sosmedstaging
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-pass
  namespace: staging
type: Opaque
data:
  DB_USER: YWRtaW4=
  DB_PASS: Njg5NWFndGtlbXM=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-php
  namespace: staging
data:
  config.php: |
      <?php
      $db_host = getenv("DB_HOST");
      $db_user = getenv("DB_USER");
      $db_pass = getenv("DB_PASS");
      $db_name = "dbsosmed";
      try {
      //create PDO connection
      $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
      } catch(PDOException $e) {
      //show error
      die("Terjadi masalah: " . $e->getMessage());
      }
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: sosmedstaging
 namespace: staging
spec:
  selector:
    matchLabels:
      run: sosmedstaging
  replicas: 4
  template:
    metadata:
      labels:
        run: sosmedstaging
    spec:
      containers:
      - name: sosmedstaging
        image: rizalkemas68/sosmed:staging
        ports:
          - containerPort: 80
        volumeMounts:
          - name: config-fb
            mountPath: "/srv/app/config.php"
            subPath: "config.php"
        env:
          - name: DB_HOST
            value: database-2.cemceonxlenm.us-east-2.rds.amazonaws.com
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-user-pass 
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-user-pass
                key: DB_PASS
      volumes:
        - name: config-fb
          configMap:
            name: config-php
---

