apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs
  namespace: default
  labels:
    app: efs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
