apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs
  namespace: default
  labels:
    app: efs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 20Gi
  selector:  
    matchlabels:
    type: "nfs-kubernetes"
