apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv0001
 namespace: production
 labels:
     type: nfs-kubernetes
spec:
 storageClassName: aws-efs1
 capacity:
     storage: 60Gi
 accessModes:
     - ReadWriteMany
 persistentVolumeReclaimPolicy: Retain
 mountOptions:
     - nfsvers=4.1
 nfs:
     path: /var/www/html/wp-content
     server: 10.10.1.207
     readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wpprod-claim
  namespace: production
spec:
  storageClassName: aws-efs1
  accessModes:
    - ReadWriteMany
  volumeName: pv0001
  resources:
    requests:
      storage: 3Gi